_wandb:
    value:
        cli_version: 0.23.1
        e:
            1vr06hpfcuen2w42ec4kousnb8tubsdc:
                apple:
                    ecpuCores: 4
                    gpuCores: 7
                    memoryGb: 8
                    name: Apple M1
                    pcpuCores: 4
                    ramTotalBytes: "8589934592"
                    swapTotalBytes: "9663676416"
                args:
                    - --dataset
                    - shapes
                    - --beta
                    - "6"
                    - --tcvae
                    - --mws-batch-size
                    - "64"
                    - --num-epochs
                    - "30"
                    - --log_freq
                    - "50"
                    - --seed
                    - "1"
                    - --tcvae
                    - --wandb
                    - --wandb_project
                    - beta-tcvae
                    - --wandb_mode
                    - online
                    - --wandb_run_name
                    - mws-bs64_seed1
                codePath: vae_quant.py
                codePathLocal: vae_quant.py
                cpu_count: 8
                cpu_count_logical: 8
                disk:
                    /:
                        total: "245107195904"
                        used: "241573793792"
                email: zoe.matrullo@gmail.com
                executable: /Users/zoe/Desktop/VAEs/beta-tcvae/.venv/bin/python
                git:
                    commit: c69b32ec464134d35584a12db3a961a897db0808
                    remote: https://github.com/zoematr/beta-tcvae.git
                host: Air-di-Zoe.fritz.box
                memory:
                    total: "8589934592"
                os: macOS-13.0.1-arm64-arm-64bit
                program: /Users/zoe/Desktop/VAEs/beta-tcvae/vae_quant.py
                python: CPython 3.11.8
                root: /Users/zoe/Desktop/VAEs/beta-tcvae
                startedAt: "2026-01-08T14:00:54.801200Z"
                writerId: 1vr06hpfcuen2w42ec4kousnb8tubsdc
        m: []
        python_version: 3.11.8
        t:
            "1":
                - 1
                - 41
            "2":
                - 1
                - 41
            "3":
                - 13
                - 16
                - 62
            "4": 3.11.8
            "5": 0.23.1
            "12": 0.23.1
            "13": darwin-arm64
batch_size:
    value: 1024
beta:
    value: 6
beta_anneal:
    value: false
conv:
    value: false
dataset:
    value: shapes
dist:
    value: normal
exclude_mutinfo:
    value: false
gpu:
    value: 0
lambda_anneal:
    value: false
latent_dim:
    value: 10
learning_rate:
    value: 0.001
log_freq:
    value: 50
mss:
    value: false
mws_batch_size:
    value: 64
num_epochs:
    value: 30
save:
    value: test1
seed:
    value: 1
tcvae:
    value: true
visdom:
    value: false
wandb:
    value: true
wandb_entity:
    value: null
wandb_mode:
    value: online
wandb_project:
    value: beta-tcvae
wandb_run_name:
    value: mws-bs64_seed1
workers:
    value: 0
